CREATE DATABASE ONTOP2
GO
USE ONTOP2
GO


CREATE TABLE TUYENBAY(
    MATB CHAR(10) , 
	NOIDEN NVARCHAR(50) , 
	NOIDI NVARCHAR(50) , 
	CONSTRAINT PK_TB PRIMARY KEY (MATB)
)

INSERT INTO TUYENBAY(MATB , NOIDEN , NOIDI)
VALUES ('TB01' , 'HA NOI' , 'HO CHI MINH'),
('TB02' , 'HA NOI' , 'LAM DONG'),
('TB03' , 'VINH' , 'HO CHI MINH'),
('TB04' ,'HO CHI MINH' , 'HA NOI')

SELECT * FROM TUYENBAY

CREATE TABLE THUCHIEN(
    SOHIEUCB CHAR(10) , 
	NGAY DATE ,
	LUONGVE INT,
	CONSTRAINT CHECK_TH PRIMARY KEY (SOHIEUCB)
)

INSERT INTO THUCHIEN(SOHIEUCB , NGAY , LUONGVE)
VALUES('SH01' , '2022-12-01' , 25),
('SH02' , '2022-11-28' , 30),
('SH03' , '2022-11-25' , 35),
('SH04' ,'2022-12-02' , 38)

DROP TABLE CHUYENBAY
CREATE TABLE CHUYENBAY(
     SOHIEUCB CHAR(10) , 
	 MATB CHAR(10) , 
	 GIOBAY NCHAR(10) , 
	 GIODEN NCHAR(10) , 
	 GIAVE NUMERIC(18 ,2),
	 GIAMGIA NUMERIC(18,2),
	 CONSTRAINT FK_CB1 FOREIGN KEY (SOHIEUCB) REFERENCES THUCHIEN(SOHIEUCB),
	 CONSTRAINT FK_CB2 FOREIGN KEY (MATB) REFERENCES TUYENBAY(MATB)
)

INSERT INTO CHUYENBAY(SOHIEUCB , MATB , GIOBAY , GIODEN , GIAVE , GIAMGIA)
VALUES('SH01' , 'TB01' , '10H' , '12H' , 11119000.00 , 120000.00),
('SH04' , 'TB01' , '20H' , '21H30' , 18000000.00 , 0.00),
('SH02' , 'TB03' , '12H' , '14H' , 21000000.00 , 100000.00),
('SH03' , 'TB04' , '14H' , '16H10' ,12000000.00 ,450000.00)


SELECT * FROM CHUYENBAY

--Hiển thị Số Hiệu Chuyến Bay, Giờ Bay, Giá Vé, của những chuyến bay có GiamGia &gt;
--300.000

SELECT SOHIEUCB , GIOBAY , GIAVE FROM CHUYENBAY
WHERE GIAMGIA >= 300.000

--4. Hiển thị danh sách các chuyến bay xuất phát ở Hà Nội, bay lúc 10h


SELECT CHUYENBAY.MATB , GIOBAY FROM CHUYENBAY
INNER JOIN TUYENBAY
ON TUYENBAY.MATB = CHUYENBAY.MATB
WHERE CHUYENBAY.GIOBAY = '10H'

--Hiển thị danh sách các mã tuyến bay, Nơi đi, Nơi đến của các tuyến bay chưa có
--chuyến bay

SELECT CHUYENBAY.MATB , NOIDI , NOIDEN FROM CHUYENBAY
INNER JOIN TUYENBAY
ON TUYENBAY.MATB = CHUYENBAY.MATB
WHERE SOHIEUCB IS NULL


--Tính tiền mỗi chuyến bay thông tin gồm theo MaTB, tổng thành tiền trong đó thành
--tiền bằng giá vé trừ giảm giá

SELECT MATB , SUM(GIAVE - GIAMGIA) AS TONG_TIEN
FROM CHUYENBAY
GROUP BY MATB

-- 7. Đưa ra các chuyến bay có lượng vé &gt;30
SELECT CHUYENBAY.SOHIEUCB FROM CHUYENBAY
INNER JOIN THUCHIEN
ON THUCHIEN.SOHIEUCB = CHUYENBAY.SOHIEUCB
WHERE THUCHIEN.LUONGVE >= 30

-- Đưa ra thông tin SoHieuCB, MaTB, NoiDi, NoiDen, Gia Ve, GiamGia


SELECT SOHIEUCB , CHUYENBAY.MATB , NOIDI , NOIDEN , GIAVE , GIAMGIA FROM CHUYENBAY
LEFT JOIN TUYENBAY
ON TUYENBAY.MATB = CHUYENBAY.MATB